<?php

namespace MDB\WishListBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WishListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishListRepository extends EntityRepository
{
}
